const city=["Tokyo",
"New York City",
"Shanghai",
"London",
"Beijing",
"Paris",
"Seoul",
"Singapore",
"Hong Kong",
"Dubai",
"Los Angeles",
"San Francisco",
"Sydney",
"Melbourne",
"Toronto",
"Zurich",
"Geneva",
"Munich",
"Frankfurt",
"Stockholm",
"Oslo",
"Copenhagen",
"Amsterdam",
"Vienna",
"Berlin",
"Helsinki",
"Barcelona",
"Madrid",
"Milan",
"Rome",
"Mumbai",
"Bangalore",
"New Delhi",
"Shenzhen",
"Guangzhou",
"Chengdu",
"Hangzhou",
"Wuhan",
"Shijiazhuang",
"Nanjing",
"Ahmedabad",
"Chennai",
"Kolkata",
"Tehran",
"Istanbul",
"Moscow",
"Saint Petersburg",
"Riyadh",
"Jeddah",
"Doha",
"Abu Dhabi",
"Hanoi",
"Ho Chi Minh City",
"Bangkok",
"Manila",
"Jakarta",
"Kuala Lumpur",
"Phnom Penh",
"Yangon",
"Colombo",
"Dhaka",
"Johannesburg",
"Cape Town",
"Nairobi",
"Lagos",
"Accra",
"São Paulo",
"Rio de Janeiro",
"Mexico City",
"Chicago",
"Dallas",
"Houston",
"Atlanta",
"Miami",
"Seattle",
"Vancouver",
"Montreal",
"Hamburg",
"Cologne",
"Athens",
"Warsaw",
"Prague",
"Budapest",
"Zagreb",
"Krakow",
"Brussels",
"Luxembourg City",
"Lyon",
"Marseille",
"Nice",
"Valencia",
"Seville",
"Zaragoza",
"Lisbon",
"Porto",
"Noida",
"Gurugram",
"Ghaziabad",
"Jaipur",
"Lucknow",
"Kanpur",
"Nagpur",
"Indore",
"Bhopal",
"Varanasi",
"Agra",
"Patna",
"Surat",
"Vadodara",
"Pune",
"Nashik",
"Coimbatore",
"Vijayawada",
"Visakhapatnam",
"Kochi",
"Thiruvananthapuram",
"Bareilly",
"Guwahati",
"Amritsar",
"Ludhiana",
"Chandigarh",
"Jodhpur",
"Rajkot",
"Madurai",
"Tiruchirappalli",
"Jalandhar",
"Bhubaneswar",
"Dehradun",
"Haridwar",
"Rishikesh",
"Nainital",
"Mussoorie",
"Haldwani",
"Almora",
"Shimla",
"Manali",
"Dharamshala",
"Buenos Aires",
"Bucharest",
"Sofia",
"Belgrade",
"Bratislava",
"Ljubljana",
"Riga",
"Vilnius",
"Tallinn",
"Reykjavik",
"Basel",
"Bern",
"Lausanne",
"Lucerne",
"Antwerp",
"Ghent",
"Bruges",
"Rotterdam",
"The Hague",
"Utrecht",
"Eindhoven",
"Groningen",
"Maastricht",
"Graz",
"Linz",
"Salzburg",
"Innsbruck",
"Klagenfurt",
"St. Petersburg",
"Novosibirsk",
"Yekaterinburg",
"Nizhny Novgorod",
"Kazan",
"Chelyabinsk",
"Omsk",
"Samara",
"Ufa",
"Rostov-on-Don",
"Krasnoyarsk",
"Voronezh",
"Perm",
"Volgograd",
"Krasnodar",
"Yaroslavl",
"Kaliningrad",
"Irkutsk",
"Vladivostok",
"Sochi",
"Sevastopol",
"Simferopol",
"Karachi",
"Lahore",
"Islamabad",
"Cairo",
"Alexandria",
"Casablanca",
"Hyderabad",
"Thane",
"Pimpri-Chinchwad",
"Faridabad",
"Meerut",
"Kalyan-Dombivali",
"Vasai-Virar",
"Srinagar",
"Aurangabad",
"Dhanbad",
"Navi Mumbai",
"Allahabad",
"Ranchi",
"Howrah",
"Jabalpur",
"Gwalior",
"Raipur",
"Kota",
"Solapur",
"Moradabad",
"Mysore",
"Tiruppur",
"Gurgaon",
"Aligarh",
"Salem",
"Warangal",
"Guntur",
"Bhiwandi",
"Saharanpur",
"Gorakhpur",
"Bikaner",
"Amravati",
"Jamshedpur",
"Bhilai",
"Cuttack",
"Firozabad",
"Nellore",
"Bhavnagar",
"Durgapur",
"Asansol",
"Rourkela",
"Nanded",
"Kolhapur",
"Ajmer",
"Akola",
"Gulbarga",
"Jamnagar",
"Ujjain",
"Loni",
"Siliguri",
"Jhansi",
"Ulhasnagar",
"Jammu",
"Sangli-Miraj & Kupwad",
"Mangalore",
"Erode",
"Belgaum",
"Ambattur",
"Tirunelveli",
"Malegaon",
"Gaya",
"Venice",
"Florence",
"Las Vegas",
"Dublin",
"Edinburgh",
"Quebec City",
"Ottawa",
"Calgary",
"Edmonton",
"Honolulu",
"Orlando",
"Washington D.C.",
"Philadelphia",
"Boston",
"Denver",
"Phoenix",
"New Orleans",
"Nashville",
"Austin",
"San Diego",
"San Jose",
"Portland",
"Salt Lake City",
"Manchester",
"Birmingham",
"Liverpool",
"Glasgow",
"Newcastle",
"Sheffield",
"Leeds",
"Bristol",
"Cardiff",
"Belfast",
"Perth",
"Adelaide",
"Gold Coast",
"Cairns",
"Auckland",
"Wellington",
"Christchurch",
"Queenstown",
"Hamilton",
"Taipei",
"Cork",
"Galway",
"Jerusalem",
"Tel Aviv",
"Durban",
"Marrakech",
"Tunis",
"Mombasa",
"Dar es Salaam",
"Kigali",
"Addis Ababa",
"Abuja",
"Cotonou",
"Luanda",
"Lusaka",
"Harare",
"Maputo",
"Windhoek",
"Gaborone",
"Antananarivo",
"Port Louis",
"Kampala",
"Bujumbura",
"Bangui",
"Libreville",
"Yaoundé",
"Douala",
"Kinshasa",
"Brazzaville",
"Bamako",
"Niamey",
"Nouakchott",
"Ouagadougou",
"Conakry",
"Freetown",
"Monrovia",
"Banjul",
"Bissau",
"Dakar",
"Praia",
"Yamoussoukro",
"Abidjan",
"Lomé",
"Malabo",
"N'Djamena",
"Khartoum",
"Juba",
"Asmara",
"Mogadishu",
"Djibouti",
"Moroni",
"Victoria",
"Saint-Denis",
"Porto-Novo",
"Dodoma",
"Lilongwe",
"Mbabane",
"Lobamba",
"Pretoria",
"Jalgaon",
"Udaipur",
"Maheshtala",
"Davanagere",
"Kozhikode",
"Kurnool",
"Rajpur Sonarpur",
"Rajahmundry",
"Bokaro",
"South Dumdum",
"Bellary",
"Patiala",
"Gopalpur",
"Agartala",
"Bhagalpur",
"Muzaffarnagar",
"Bhatpara",
"Panihati",
"Latur",
"Dhule",
"Rohtak",
"Sagar",
"Korba",
"Bhilwara",
"Berhampur",
"Muzaffarpur",
"Ahmednagar",
"Mathura",
"Kollam",
"Avadi",
"Kadapa",
"Kamarhati",
"Sambalpur",
"Bilaspur",
"Shahjahanpur",
"Satara",
"Bijapur",
"Rampur",
"Shimoga",
"Chandrapur",
"Junagadh",
"Thrissur",
"Alwar",
"Bardhaman",
"Kulti",
"Nizamabad",
"Parbhani",
"Tumkur",
"Khammam",
"Ozhukarai",
"Bihar Sharif",
"Panipat",
"Darbhanga",
"Bally",
"Aizawl",
"Dewas",
"Ichalkaranji",
"Karnal",
"Bathinda",
"Jalna",
"Eluru",
"Barasat",
"Kirari Suleman Nagar",
"Purnia",
"Satna",
"Mau",
"Sonipat",
"Farrukhabad",
"Durg",
"Imphal",
"Ratlam",
"Hapur",
"Arrah",
"Anantapur",
"Karimnagar",
"Etawah",
"Ambarnath",
"North Dumdum",
"Bharatpur",
"Begusarai",
"Gandhidham",
"Baranagar",
"Tiruvottiyur",
"Puducherry",
"Sikar",
"Thoothukudi",
"Rewa",
"Mirzapur",
"Raichur",
"Pali",
"Ramagundam",
"Silchar",
"Vijayanagaram",
"Tenali",
"Nagercoil",
"Sri Ganganagar",
"Karawal Nagar",
"Mango",
"Thanjavur",
"Bulandshahr",
"Uluberia",
"Katihar",
"Sambhal",
"Singrauli",
"Nadiad",
"Secunderabad",
"Naihati",
"Yamunanagar",
"Bidhannagar",
"Pallavaram",
"Bidar",
"Munger",
"Panchkula",
"Burhanpur",
"Raurkela Industrial Township",
"Kharagpur",
"Dindigul",
"Gandhinagar",
"Hospet",
"Nangloi Jat",
"Malda",
"Ongole",
"Deoghar",
"Chapra",
"Haldia",
"Khandwa",
"Nandyal",
"Morena",
"Amroha",
"Anand",
"Bhind",
"Bhalswa Jahangir Pur",
"Madhyamgram",
"Bhiwani",
"Berhampore",
"Ambala",
"Morbi",
"Fatehpur",
"Raebareli",
"Khora",
"Bhusawal",
"Orai",
"Bahraich",
"Vellore",
"Mehsana",
"Raiganj",
"Sirsa",
"Danapur",
"Serampore",
"Sultan Pur Majra",
"Guna",
"Jaunpur",
"Panvel",
"Shivpuri",
"Surendranagar Dudhrej",
"Unnao",
"Hugli-Chinsurah",
"Alappuzha",
"Kottayam",
"Machilipatnam",
"Adoni",
"Udupi",
"Katni",
"Virar",
"Karur",
"Palakkad",
"Palanpur",
"Sankt Peterburg",
"Bijnor",
"Dharmavaram"];
let result
const input=document.getElementById('input1');
input.addEventListener('input',function(e){
    e.preventDefault();
    let val=input.value;
    if(val!=''){
        let result1=city.filter((i)=>{
            return i.toLowerCase().startsWith(val.toLowerCase());
        })
        let result2
        if(result1.length<10){
            
            result2=city.filter((i)=>{
                return i.toLowerCase().includes(val.toLowerCase()) && !(i.toLowerCase().startsWith(val.toLowerCase()));
            })
            
        }
        result=result1.concat(result2);
        display(result);
    }
    else{
        document.getElementById('3').innerHTML='';
    }
    if (document.getElementById('3').getElementsByTagName('li').length > 0) {
        document.getElementById('3').classList.add('has-items');
    }
    else document.getElementById('3').classList.remove('has-items');


})
const list=document.getElementById('3')

function selectItem(item) {
    const selected = list.querySelector('.selected');
    if (selected) {
        selected.classList.remove('selected');
    }
    item.classList.add('selected');
    // input.value = item.innerHTML;
}


list.addEventListener('mouseover', function(event) {
    const target = event.target;
    // console.log(target)
    if (target.tagName === 'LI') {
        selectItem(target);
    }
});


list.addEventListener('mouseout', function(event) {
    //related target yani jaha gaya 
    const relatedTarget = event.relatedTarget;
    if (!relatedTarget || (relatedTarget && relatedTarget.parentNode !== list)) {
        const selected = list.querySelector('.selected');
        if (selected) {
            selected.classList.remove('selected');
        }
        // input.value = ''; 
    }
});
document.addEventListener('keyup', function(e) {
    e.preventDefault();
    if (list.getElementsByTagName('li').length > 0) {
        const selectedIndex = Array.from(list.getElementsByTagName('li')).findIndex(li => li.classList.contains('selected'));
        // console.log(selectedIndex);
        if (e.key === 'ArrowUp' && selectedIndex > 0) {
            list.getElementsByTagName('li')[selectedIndex].classList.remove('selected');
            list.getElementsByTagName('li')[selectedIndex - 1].classList.add('selected');
            input.value=list.getElementsByTagName('li')[selectedIndex - 1].innerHTML;
        } else if (e.key === 'ArrowDown' && selectedIndex < list.getElementsByTagName('li').length - 1&&selectedIndex <9) {
            if (selectedIndex >= 0) {
                list.getElementsByTagName('li')[selectedIndex].classList.remove('selected');
            }
            if(selectedIndex <9){
                list.getElementsByTagName('li')[selectedIndex + 1].classList.add('selected');
                input.value=list.getElementsByTagName('li')[selectedIndex + 1].innerHTML;
            }
        } else if (e.key === 'Enter') {
            const selectedItem = list.querySelector('.selected');
            if (selectedItem) {
                put(selectedItem);
            }
        }

    }
});


function display(result){
    const content=result.map((res)=>{
        if (res !== undefined) {
            return "<li onclick=put(this)>"+res+"</li>"
        } 
    })
    document.getElementById('3').innerHTML=content.join('');
}
function put(list){
    input.value=list.innerHTML;
    document.getElementById('3').innerHTML='';
    document.getElementById('3').classList.remove('has-items')
}